"""Phase 06 freeze: write ``configs/frozen/<optimizer>.yaml`` from the sweep's selection.

Reads ``runs/tuning/selection.json`` (written by ``scripts/tpu/tune.py``) and writes, for each
optimizer, the selected peak learning rate and secondary knob under the key ``optimizer`` (the
format ``scripts/tpu/main_runs.py`` reads), with the selection scores as provenance. Every other
setting stays at ``configs/base_125m.yaml``. After this script: commit, tag ``tuning-frozen``.

Usage: python scripts/tpu/freeze_configs.py
"""

from __future__ import annotations

import json
import pathlib

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[2]
KNOB = {"adamw": "b2", "soap": "shampoo_beta", "gimbal": "rot_rate"}


def main() -> None:
    sel = json.loads((ROOT / "runs" / "tuning" / "selection.json").read_text())
    snapshot = (ROOT / "runs" / "tuning" / "SNAPSHOT").read_text().strip()
    commit = (pathlib.Path(snapshot) / "SNAPSHOT_COMMIT").read_text().strip()
    out = ROOT / "configs" / "frozen"
    out.mkdir(parents=True, exist_ok=True)
    for opt, knob in KNOB.items():
        s = sel[opt]
        doc = {
            "optimizer": {"lr": float(s["lr"]), knob: float(s[knob])},
            "provenance": {
                "selection": "runs/tuning/selection.json",
                "tuning_code_commit": commit,
                "rule": "Phase 06: lowest mean final validation loss over seeds 0 and 1 "
                        "(ties within 0.002 nats: smaller learning rate; Stage C ties keep "
                        "the default)",
                "stage_a_mean_val_loss": {k: (None if v == float("inf") else float(v))
                                          for k, v in s["stage_a_scores"].items()},
                "stage_c_mean_val_loss": {str(k): (None if v == float("inf") else float(v))
                                          for k, v in s["stage_c_scores"].items()},
            },
        }
        text = ("# Frozen after Phase 06 (tag tuning-frozen); generated by "
                "scripts/tpu/freeze_configs.py. Changes only through protocol section 5.\n"
                + yaml.safe_dump(doc, sort_keys=False))
        (out / f"{opt}.yaml").write_text(text)
        print(opt, doc["optimizer"])


if __name__ == "__main__":
    main()
