"""G7.3: compute per optimizer (tuning and confirmatory runs) in TPU v4 chip-hours.

Reads the driver logs (``runs/logs/tune.log`` from ``scripts/tpu/tune.py`` and
``runs/logs/main_runs.log`` from ``scripts/tpu/main_runs.py``), whose per-launch lines give the
wall-clock time the slice was held, from process start to exit, so start-up, compilation,
evaluation and every retry are included. Each launch holds all 16 chips. Writes
``analysis/results/compute.json`` and ``analysis/results/compute.md``.

Usage: python analysis/compute_budget.py
"""

from __future__ import annotations

import json
import pathlib
import re
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "analysis" / "results"
CHIPS = 16
OPTS = ("adamw", "soap", "gimbal")
# "00:06:49 adamw_lr0.000125_s1 exit=0 attempt=0 482s {...}" (tune.py) and
# "12:00:00 gimbal/seed2 attempt=0 exit=0 1834s {...}" (main_runs.py)
LINE = re.compile(
    r"^\d\d:\d\d:\d\d (\S+) (?:exit=-?\d+ attempt=\d+|attempt=\d+ exit=-?\d+) "
    r"(\d+)s "
)


def launches(path: pathlib.Path) -> list[tuple[str, int]]:
    if not path.exists():
        return []
    out = []
    for line in path.read_text().splitlines():
        m = LINE.match(line)
        if m:
            out.append((m.group(1), int(m.group(2))))
    return out


DIAG = re.compile(r"^(\d\d):(\d\d):(\d\d) (start|end) (\S+)")
DIAG_OPT = {"d6_soap_b1_09": "soap"}  # the other F-032 diagnostics ran Gimbal


def diagnostics() -> dict:
    """F-032 diagnostic runs (``runs/logs/diag/*.log``: start and end times of each launch)."""
    per = defaultdict(lambda: {"launches": 0, "seconds": 0})
    for log in sorted((ROOT / "runs" / "logs" / "diag").glob("*.log")):
        start = {}
        for line in log.read_text().splitlines():
            m = DIAG.match(line)
            if not m:
                continue
            sec = int(m.group(1)) * 3600 + int(m.group(2)) * 60 + int(m.group(3))
            if m.group(4) == "start":
                start[m.group(5)] = sec
            elif m.group(5) in start:
                opt = DIAG_OPT.get(m.group(5), "gimbal")
                per[opt]["launches"] += 1
                per[opt]["seconds"] += (sec - start.pop(m.group(5))) % 86400
    return per


def main() -> None:
    res: dict = {"chips": CHIPS, "stages": {}}
    for stage, log in (("tuning", "tune.log"), ("main", "main_runs.log")):
        per = defaultdict(lambda: {"launches": 0, "seconds": 0})
        for name, sec in launches(ROOT / "runs" / "logs" / log):
            opt = name.split("_")[0].split("/")[0]
            per[opt]["launches"] += 1
            per[opt]["seconds"] += sec
        res["stages"][stage] = {
            o: dict(per[o], chip_hours=per[o]["seconds"] * CHIPS / 3600) for o in OPTS
        }
    per = diagnostics()
    res["stages"]["diagnostics"] = {
        o: dict(per[o], chip_hours=per[o]["seconds"] * CHIPS / 3600) for o in OPTS
    }
    res["total_chip_hours"] = {
        o: sum(res["stages"][s][o]["chip_hours"] for s in res["stages"]) for o in OPTS
    }
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "compute.json").write_text(json.dumps(res, indent=1))
    lines = [
        "# Compute per optimizer (generated by `analysis/compute_budget.py`)",
        "",
        f"Wall-clock time the slice was held per launch × {CHIPS} TPU v4 chips "
        "(start-up, compilation, evaluation and retries included).",
        "",
        "| optimizer | tuning launches | tuning chip-hours | diagnostic launches (F-032) | "
        "diagnostic chip-hours | main launches | main chip-hours | total chip-hours |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for o in OPTS:
        t, m = res["stages"]["tuning"][o], res["stages"]["main"][o]
        d = res["stages"]["diagnostics"][o]
        lines.append(
            f"| {o} | {t['launches']} | {t['chip_hours']:.1f} | {d['launches']} | "
            f"{d['chip_hours']:.1f} | {m['launches']} | {m['chip_hours']:.1f} | "
            f"{res['total_chip_hours'][o]:.1f} |"
        )
    (OUT / "compute.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
