"""Phase 06 report: budget table, every trial, selected values, learning-rate curves.

Reads ``runs/tuning/*/final.json`` and ``runs/tuning/selection.json`` (written by
``scripts/tpu/tune.py``); writes ``research/ledger/tuning.md`` and
``analysis/results/tuning_lr_curves.png``. Every number comes from those files.

Usage: python analysis/tuning_report.py
"""

from __future__ import annotations

import json
import pathlib
import re
from collections import defaultdict

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
RUNS = ROOT / "runs" / "tuning"
OUT = ROOT / "research" / "ledger" / "tuning.md"
FIG = ROOT / "analysis" / "results" / "tuning_lr_curves.png"
NAME = re.compile(
    r"^(adamw|soap|gimbal)_lr([0-9.e-]+)(?:_(b2|shampoo_beta|rot_rate)([0-9.]+))?"
    r"_s(\d+)$"
)
OPTS = ("adamw", "soap", "gimbal")
KNOB = {"adamw": ("b2", 0.95), "soap": ("shampoo_beta", 0.95), "gimbal": ("rot_rate", 0.05)}


def trials() -> list[dict]:
    rows = []
    for d in sorted(RUNS.iterdir()):
        m = NAME.match(d.name)
        if not m or not (d / "final.json").exists():
            continue
        fin = json.loads((d / "final.json").read_text())
        opt, lr, key, val, seed = m.groups()
        rows.append(
            {
                "run": d.name,
                "optimizer": opt,
                "lr": float(lr),
                "knob": key or KNOB[opt][0],
                "value": float(val) if val else KNOB[opt][1],
                "seed": int(seed),
                "stage": "C" if key else "A",
                "diverged": bool(fin.get("diverged")),
                "val_loss": fin.get("val_loss"),
                "seconds": fin.get("train_seconds"),
            }
        )
    return rows


def main() -> None:
    rows = trials()
    sel_path, snap_path = RUNS / "selection.json", RUNS / "SNAPSHOT"
    sel = json.loads(sel_path.read_text()) if sel_path.exists() else {}
    snap = snap_path.read_text().strip() if snap_path.exists() else "?"
    lines = [
        "# Phase 06 tuning (generated by `analysis/tuning_report.py`)",
        "",
        "Protocol after D-003: 125M model, 2,500 steps of 240 × 1024 tokens (614M tokens), "
        "seeds 0 and 1, selection on the mean final loss over the full 20M-token "
        "validation split; Stage A learning-rate grid (7 points, factor 2, edge "
        "extensions offered to every optimizer), Stage C one secondary knob (3 values). "
        f"Driver `scripts/tpu/tune.py`, one frozen code snapshot (`{snap}`).",
        "",
        "## Budget (G6.1)",
        "",
        "| optimizer | Stage A runs | Stage C runs | total | diverged | TPU hours (16 chips) |",
        "|---|---|---|---|---|---|",
    ]
    for opt in OPTS:
        r = [x for x in rows if x["optimizer"] == opt]
        a = sum(x["stage"] == "A" for x in r)
        c = sum(x["stage"] == "C" for x in r)
        hours = sum(x["seconds"] or 0 for x in r) / 3600
        lines.append(
            f"| {opt} | {a} | {c} | {a + c} | {sum(x['diverged'] for x in r)} | "
            f"{hours:.2f} h × 16 chips |"
        )
    lines += ["", "## Stage A: mean final validation loss by learning rate (two seeds)", ""]
    fig, ax = plt.subplots(figsize=(6.5, 4))
    for opt in OPTS:
        by_lr = defaultdict(list)
        for x in rows:
            if x["optimizer"] == opt and x["stage"] == "A":
                by_lr[x["lr"]].append(
                    np.inf if x["diverged"] or x["val_loss"] is None else x["val_loss"]
                )
        cells = []
        xs, ys = [], []
        for lr in sorted(by_lr):
            v = by_lr[lr]
            mean = float(np.mean(v))  # inf if a seed diverged
            cells.append(
                f"{lr:.4g}: "
                + ("div" if not np.isfinite(mean) else f"{mean:.4f}")
                + ("" if len(v) == 2 else f" ({len(v)}/2 seeds)")
            )
            if np.isfinite(mean) and len(v) == 2:
                xs.append(lr)
                ys.append(mean)
        lines.append(f"* **{opt}**: " + "; ".join(cells))
        ax.plot(xs, ys, marker="o", label=opt)
    ax.set_xscale("log")
    ax.set_xlabel("peak learning rate")
    ax.set_ylabel("final validation loss (mean of 2 seeds)")
    ax.legend()
    ax.grid(alpha=0.3)
    FIG.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(FIG, dpi=150)
    lines += ["", f"Figure: `{FIG.relative_to(ROOT)}`.", "", "## Stage C and selection", ""]
    for opt in OPTS:
        if opt not in sel:
            lines.append(f"* {opt}: pending")
            continue
        s = sel[opt]
        key = KNOB[opt][0]
        sc = ", ".join(f"{k}: {v:.4f}" for k, v in s["stage_c_scores"].items())
        lines.append(
            f"* **{opt}**: learning rate {s['lr']:.4g}; {key} = {s[key]} "
            f"(Stage C mean losses {sc}); ties within 0.002 nats keep the default."
        )
    edge = {}
    for opt in OPTS:
        lrs = sorted({x["lr"] for x in rows if x["optimizer"] == opt and x["stage"] == "A"})
        if opt in sel and lrs:
            edge[opt] = sel[opt]["lr"] in (lrs[0], lrs[-1])
    if edge:
        knob_edge = {}
        for o in OPTS:
            if o in sel:
                grid = [float(v) for v in sel[o]["stage_c_scores"]]
                knob_edge[o] = float(sel[o][KNOB[o][0]]) in (min(grid), max(grid))
        lines += [
            "",
            "G6.2 (no selected value on a grid edge): learning rates "
            + ", ".join(f"{k}: {'edge' if v else 'interior'}" for k, v in edge.items())
            + "; secondary knobs: "
            + ", ".join(f"{k}: {'edge' if v else 'interior'}" for k, v in knob_edge.items())
            + ".",
        ]
    lines += [
        "",
        "## All trials",
        "",
        "| run | stage | optimizer | lr | knob | seed | final validation loss | diverged | "
        "train seconds |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for x in sorted(
        rows, key=lambda r: (r["optimizer"], r["stage"], r["lr"], r["value"], r["seed"])
    ):
        vl = "" if x["val_loss"] is None else f"{x['val_loss']:.4f}"
        lines.append(
            f"| {x['run']} | {x['stage']} | {x['optimizer']} | {x['lr']:.4g} | "
            f"{x['knob']}={x['value']} | {x['seed']} | {vl} | {x['diverged']} | "
            f"{x['seconds']:.0f} |"
        )
    OUT.write_text("\n".join(lines) + "\n")
    print("\n".join(lines[:40]))


if __name__ == "__main__":
    main()
