"""Phase 08: write ``analysis/decision.md`` from ``analysis/results/phase08.json``.

The decision rule is applied in ``analysis/phase08.py``; this script states its outcome, the
observations and diagnostics behind it (every number read from the generated results), the
classification of the outcome under the protocol (§4) and what follows (§9, D-011). The test split
is opened only after this file exists (``scripts/tpu/eval_test.py``).

Usage: python analysis/write_decision.py
"""

from __future__ import annotations

import json
import pathlib

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
RES = ROOT / "analysis" / "results" / "phase08.json"
OUT = ROOT / "analysis" / "decision.md"
NAMES = {"adamw": "AdamW", "soap": "SOAP", "gimbal": "Gimbal"}


def yes(b: bool) -> str:
    return "**yes**" if b else "**no**"


def main() -> None:
    r = json.loads(RES.read_text())
    runs, paired, dec = r["runs"], r["paired"], r["decision"]

    def val(o, s):
        return runs[f"{o}/seed{s}"]["val_loss"]

    def mech(key):
        vals = [runs[f"gimbal/seed{s}"]["mechanism"].get(key) for s in (2, 3)]
        return [v for v in vals if v is not None]

    k_attn = mech("attn/kappa_noise_corrected_median/final")
    k_mlp = mech("mlp/kappa_noise_corrected_median/final")
    c_attn = mech("attn/shrink_c_median/final")
    c_mlp = mech("mlp/shrink_c_median/final")

    def probe(opt, prefix):
        out = []
        for s in (2, 3):
            m = runs.get(f"{opt}/seed{s}", {}).get("mechanism", {})
            out += [
                v for k, v in m.items() if k.startswith(prefix) and k.endswith("own_minus_pooled")
            ]
        return out

    ahead, n_ev, lead = {}, {}, {}
    for s in (2, 3):
        curves = {}
        for o in ("gimbal", "soap"):
            path = ROOT / "runs" / "main" / o / f"seed{s}" / "eval.jsonl"
            curves[o] = {
                x["step"]: x["val_loss_subset"]
                for x in map(json.loads, path.read_text().splitlines())
                if "val_loss_subset" in x
            }
        steps = sorted(set(curves["gimbal"]) & set(curves["soap"]))
        ahead[s] = sum(curves["gimbal"][t] < curves["soap"][t] for t in steps)
        n_ev[s] = len(steps)
        lead[s] = max(curves["soap"][t] - curves["gimbal"][t] for t in steps)

    lines = [
        "# Phase 08 decision: Gimbal against AdamW and SOAP at 125M parameters / 2.5B tokens",
        "",
        "Generated by `analysis/write_decision.py` from `analysis/results/phase08.json` "
        "(`python analysis/phase08.py`; tables in `analysis/results/phase08_tables.md`). The rule "
        "and its definitions were fixed before the confirmatory runs (`phases/08_*.md`, D-005).",
        "",
        "## Decision rule outcome",
        "",
        "| | AdamW | SOAP |",
        "|---|---|---|",
        f"| Gimbal beats it on loss (both seeds lower and mean paired difference beyond twice "
        f"the pooled bootstrap SE, {2 * r['pooled_within_run_se']:.4f}) | "
        f"{yes(dec['beats_on_loss']['adamw'])} | {yes(dec['beats_on_loss']['soap'])} |",
        f"| Gimbal beats it on wall-clock (lower step time, or less wall-clock to its final loss) "
        f"| {yes(dec['beats_on_wallclock']['adamw'])} | {yes(dec['beats_on_wallclock']['soap'])} |",
        "",
        f"No slower than SOAP per step: {yes(dec['no_slower_than_soap'])}. Headline claim "
        f'("Gimbal outperforms SOAP and its peers"): '
        f"**{'allowed' if dec['headline_claim_allowed'] else 'not allowed'}**.",
        "",
        "## What was observed",
        "",
        "| optimizer | seed 2 | seed 3 | mean | steady-state step (ms) |",
        "|---|---|---|---|---|",
    ]
    for o in ("adamw", "soap", "gimbal"):
        st = np.mean([runs[f"{o}/seed{s}"]["steady_state_step_s"] for s in (2, 3)])
        lines.append(
            f"| {NAMES[o]} | {val(o, 2):.4f} | {val(o, 3):.4f} | "
            f"{(val(o, 2) + val(o, 3)) / 2:.4f} | {1e3 * st:.1f} |"
        )
    lines += [
        "",
        f"Final validation loss (mean token cross-entropy, 20M tokens). Pooled within-run "
        f"bootstrap SE {r['pooled_within_run_se']:.4f}; seed-to-seed SD pooled over optimizers "
        f"{r['pooled_seed_sd']:.4f}.",
        "",
    ]
    for c in ("adamw", "soap"):
        p = paired[c]
        per = p["per_seed"]
        diffs = ", ".join(f"{e['gimbal_minus']:+.4f}" for e in per.values())
        ses = ", ".join(f"{e['paired_bootstrap_se']:.4f}" for e in per.values())
        mult = [e["token_multiplier"] for e in per.values()]
        mtxt = ", ".join(f"{m:.3f}" if m else "not reached" for m in mult)
        lines.append(
            f"* Gimbal − {NAMES[c]} by seed: {diffs} (paired bootstrap SE {ses}); token "
            f"multiplier by seed: {mtxt}."
        )
    lines += [
        "",
        "## Diagnostics",
        "",
        "* Premise. The noise-corrected non-separability index of Gimbal's flow variances "
        "(median over the matrices of a bucket, final step) is "
        f"{', '.join(f'{v:.4f}' for v in k_attn)} (attention, seeds 2 and 3) and "
        f"{', '.join(f'{v:.4f}' for v in k_mlp)} (MLP), against the "
        "predeclared premise threshold 0.05: the rotated variances are close to separable, as on "
        f"the small model (F-030). The empirical-Bayes factor is accordingly small "
        f"({', '.join(f'{v:.3f}' for v in c_attn + c_mlp)}): Gimbal's variance weights are "
        "almost the separable fit, i.e. close to KL-Shampoo's.",
        f"* Frame quality at the end (D-005 item 8): on held-out validation gradients each run's "
        f"own "
        f"frame beats a pooled-factor frame fitted to 16 fresh gradients in "
        f"{sum(v < 0 for v in probe('gimbal', 'probe/'))}/{len(probe('gimbal', 'probe/'))} "
        f"matrices for Gimbal and {sum(v < 0 for v in probe('soap', 'probe/'))}/"
        f"{len(probe('soap', 'probe/'))} for SOAP.",
        f"* Frame quality at step 1,000 (exploratory, D-009, seed 2): own frame better than the "
        f"fresh pooled frame in {sum(v < 0 for v in probe('gimbal', 'probe_step1000/'))}/"
        f"{len(probe('gimbal', 'probe_step1000/'))} matrices for Gimbal and "
        f"{sum(v < 0 for v in probe('soap', 'probe_step1000/'))}/"
        f"{len(probe('soap', 'probe_step1000/'))} for SOAP. On the evaluation curves (every 250 "
        f"steps) Gimbal was ahead of SOAP at {ahead[2]}/{n_ev[2]} (seed 2) and "
        f"{ahead[3]}/{n_ev[3]} (seed 3) "
        f"evaluations, by up to {max(lead.values()):.3f} nats, and SOAP caught up as the learning "
        "rate decayed (`analysis/results/loss_curves.png`).",
        "* Stability: no loss spikes (D-005 definition) in any run; frames orthogonal to about "
        "1e-6 throughout.",
        "",
        "## Classification (protocol §4)",
        "",
        "* Against SOAP: **effect smaller than noise** (mixed signs over the two seeds, a mean "
        "difference far below the threshold and of the order of the seed-to-seed spread) and "
        "**mechanism prediction falsified** at its premise (the non-separability the likelihood "
        "frame exploits is nearly absent); plus a **wall-clock loss** (Gimbal's step is slower, "
        "as measured in Phase 04, G4.2).",
        "* Against AdamW: the predicted advantage of a Kronecker-frame method is confirmed.",
        "",
        "## What happens next (D-011)",
        "",
        "The protocol's escalation condition applies: the central claim (Gimbal beats SOAP) is "
        "not supported after the protocol was followed, including one repair cycle (F-032/C-019) "
        "and "
        "equal-budget tuning, and the mechanism's premise fails at both scales studied. Protocol "
        "§9 "
        "asks to report the negative result with its evidence rather than to search for a "
        "configuration that reverses it; the owner instructed the work to be completed without "
        "questions, so no further repair cycle is run and the result is reported as it is. The "
        "test split is evaluated once, after this file, for the paper.",
        "",
        "The next experiments with the most information, not run here:",
        "",
        "1. Gimbal's tuning was not complete in one dimension: its rotation rate was selected at "
        "the edge of its grid (faster frames kept helping). A larger rate (and the early-phase "
        "schedule of the frame, which the tuning runs show to be fragile at high learning rates) "
        "is the cheapest test of whether the remaining gap to SOAP closes.",
        "2. KL-SOAP, which beat Gimbal on the small model under separable statistics, at 125M.",
        "3. Settings where the rotated variances are measured to be non-separable (other "
        "architectures or layers; the last MLP projection has the largest pooled-frame index "
        "among the probed matrices), where the theory predicts the likelihood frame to matter.",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print("\n".join(lines[:22]))


if __name__ == "__main__":
    main()
